-- PROJETO PILOTO: use somente dados fictícios.

create table if not exists public.clientes (
    id uuid primary key default gen_random_uuid(),
    created_at timestamptz not null default now(),
    nome text not null,
    telefone text not null default '',
    email text not null default '',
    endereco text not null default ''
);

create table if not exists public.orcamentos (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    cliente_id uuid not null references public.clientes(id),
    status text not null default 'Orçamento' check (
        status in (
            'Orçamento', 'Aguardando aprovação', 'Aprovado', 'Em produção',
            'Pronto', 'Instalação', 'Concluído', 'Cancelado'
        )
    ),
    validade date,
    instalacao boolean not null default false,
    valor_instalacao numeric(12,2) not null default 0,
    valor_total numeric(12,2) not null default 0,
    observacoes text not null default '',
    arquivo_gerado boolean not null default false,
    arquivo_gerado_em timestamptz
);

create table if not exists public.itens_orcamento (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    orcamento_id bigint not null references public.orcamentos(id) on delete cascade,
    ambiente text not null default '',
    tipo_vidro text not null,
    espessura_mm numeric(6,2) not null,
    largura_mm numeric(10,2) not null,
    altura_mm numeric(10,2) not null,
    quantidade integer not null default 1 check (quantidade > 0),
    acabamento text not null default '',
    preco_m2 numeric(12,2) not null default 0,
    area_m2 numeric(12,3) not null default 0,
    valor_item numeric(12,2) not null default 0
);

create or replace function public.atualizar_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists orcamentos_updated_at on public.orcamentos;
create trigger orcamentos_updated_at
before update on public.orcamentos
for each row execute function public.atualizar_updated_at();

alter table public.clientes enable row level security;
alter table public.orcamentos enable row level security;
alter table public.itens_orcamento enable row level security;

-- Políticas abertas apenas para o piloto com dados fictícios.
-- Antes de usar com clientes reais, implemente login e políticas por usuário.
drop policy if exists "piloto_clientes_select" on public.clientes;
drop policy if exists "piloto_clientes_insert" on public.clientes;
drop policy if exists "piloto_orcamentos_select" on public.orcamentos;
drop policy if exists "piloto_orcamentos_insert" on public.orcamentos;
drop policy if exists "piloto_orcamentos_update" on public.orcamentos;
drop policy if exists "piloto_itens_select" on public.itens_orcamento;
drop policy if exists "piloto_itens_insert" on public.itens_orcamento;

create policy "piloto_clientes_select" on public.clientes for select to anon using (true);
create policy "piloto_clientes_insert" on public.clientes for insert to anon with check (true);
create policy "piloto_orcamentos_select" on public.orcamentos for select to anon using (true);
create policy "piloto_orcamentos_insert" on public.orcamentos for insert to anon with check (true);
create policy "piloto_orcamentos_update" on public.orcamentos for update to anon using (true) with check (true);
create policy "piloto_itens_select" on public.itens_orcamento for select to anon using (true);
create policy "piloto_itens_insert" on public.itens_orcamento for insert to anon with check (true);

grant select, insert on public.clientes to anon;
grant select, insert, update on public.orcamentos to anon;
grant select, insert on public.itens_orcamento to anon;
grant usage, select on all sequences in schema public to anon;

